export const teamData = [
  {
    id: "1",
    image: "/images/about/teamImg1.svg",
    name: "Olivia Rhye",
    designation: "Construction Supervisor",
    rating: 5,
  },
  {
    id: "2",
    image: "/images/about/teamImg2.png",
    name: "Phoenix Baker",
    designation: "Client Relations Specialist",
    rating: 5,
  },
  {
    id: "3",
    image: "/images/about/teamImg3.png",
    name: "Lana Steiner",
    designation: "Architectural Consultant",
    rating: 5,
  },
  {
    id: "4",
    image: "/images/about/teamImg4.png",
    name: "Demi Wilkinson",
    designation: "Interior Stylist",
    rating: 5,
  },
  {
    id: "5",
    image: "/images/about/teamImg5.png",
    name: "Olivia Rhye",
    designation: "Construction Supervisor",
    rating: 5,
  },
  {
    id: "6",
    image: "/images/about/teamImg6.png",
    name: "Phoenix Baker",
    designation: "Client Relations Specialist",
    rating: 5,
  },
  {
    id: "7",
    image: "/images/about/teamImg7.png",
    name: "Lana Steiner",
    designation: "Architectural Consultant",
    rating: 5,
  },
  {
    id: "8",
    image: "/images/about/teamImg8.png",
    name: "Demi Wilkinson",
    designation: "Interior Stylist",
    rating: 5,
  },
  {
    id: "9",
    image: "/images/about/teamImg1.svg",
    name: "Grace Turner",
    designation: "Construction Supervisor",
    rating: 5,
  },
  {
    id: "10",
    image: "/images/about/teamImg2.png",
    name: "John Anderson",
    designation: "Architectural Consultant",
    rating: 5,
  },
  {
    id: "11",
    image: "/images/about/teamImg3.png",
    name: "Emma Robinson",
    designation: "Interior Stylist",
    rating: 5,
  },
  {
    id: "12",
    image: "/images/about/teamImg4.png",
    name: "Oscar Taylor",
    designation: "Architectural Consultant",
    rating: 5,
  },
];
